# Generated by Django 5.0.6 on 2024-05-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = False

    dependencies = []

    # operations = [
    #     migrations.CreateModel(
    #         name="User",
    #         fields=[
    #             ("id", models.AutoField(primary_key=True, serialize=False)),
    #             ("username", models.CharField(max_length=255)),
    #             ("email", models.EmailField(max_length=254, unique=True)),
    #             ("password", models.CharField(max_length=255)),
    #             ("roles", models.TextField(blank=True, null=True)),
    #         ],
    #         options={
    #             "db_table": "user",
    #         },
    #     ),
    # ]
